name: hex_canvas_mobile
description: Hexagonal canvas with nodes, edges, pan and zoom.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.0
  http: ^1.2.0
  hive_flutter: ^1.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.0
  flutter_markdown: ^0.7.3
  share_plus: ^10.0.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
